### ISSUE TITLE
Dataset scenes visualização 

### ISSUE THREAD

**Issue by ritapm18** [miguelriemoliveira/savi_23-24#10]
Olá professor,
É normal/suposto as point clouds do dataset das cenas abrirem assim?
![IMG-20240106-WA0003](https://github.com/miguelriemoliveira/savi_23-24/assets/145997318/66817ed5-5921-4554-8f5e-a696b2e1348e)
Fiz download dos ficheiros errados? 

Cumprimentos 
Rita Moreira

**Comment by miguelriemoliveira** [comment]
Olá @ritapm18 ,

como está a abrir os ficheiros?

o que mostra parecem ser cores falsas a representar a altura ou outra dimensão cartesiana.
Estas cores podem já estar incluídas no ficheiro, mas o mais provável é que seja o software que está a utilizar para visualizar o ficheiro que está a criar e mostrar estas cores.

**Comment by ritapm18** [comment]
Estou a fazer como o professor ensinou, 
o3d.io.read_point_cloud()
E depois 
o3d.visualization.draw_geometries(entities,
                                    zoom=0.3412,
                                    front=view['trajectory'][0]['front'],
                                    lookat=view['trajectory'][0]['lookat'],
                                    up=view['trajectory'][0]['up'])

**Comment by ritapm18** [comment]
Fiz download deste dataset:
Entire RGB-D Scenes Dataset v.2
[rgbd-scenes-v2_pc.zip](https://rgbd-dataset.cs.washington.edu/dataset/rgbd-scenes-v2/rgbd-scenes-v2_pc.zip) (189 MB) - Aligned scene point clouds, ground truth annotations, and camera pose estimates from 3D scene reconstruction

**Comment by miguelriemoliveira** [comment]
Olá @rritapm18,

consegue enviar-me pff uma nuvem de pontos em que isto aconteça, e o link para o código para executar a leitura e visualização.

**Comment by ritapm18** [comment]
Olá professor, 
acontece em todas elas... 
Vou enviar lhe por email, por aqui não consigo carregar a nuvem pq n suporta ficheiros '.ply'.

**Comment by ritapm18** [comment]
```python
from copy import deepcopy
import math
import open3d as o3d
import numpy as np
from matplotlib import cm
from more_itertools import locate

view = {
    "class_name": "ViewTrajectory",
    "interval": 29,
    "is_loop": False,
    "trajectory":
        [
            {
                "boundingbox_max": [2.6540005122611348, 2.3321821423160629, 0.85104994623420782],
                "boundingbox_min": [-2.5261458770339673, -2.1656718060235378, -0.55877501755379944],
                "field_o_view": 60.0,
                "front": [0.75672239933786944, 0.34169632162348007, 0.55732830013316348],
                "lookat": [0.046395260625899069, 0.011783639768603466, -0.10144691776517496],
                "up": [-0.50476400916821107, -0.2363660920597864, 0.83026764695055955],
                "zoom": 0.30119999999999997
            }
        ],
    "version_major": 1,
    "version_minor": 0
}


# -----------------------------------------------------------------
# Initialization
# -----------------------------------------------------------------
pcd_downsampled = o3d.io.read_point_cloud('data/scenes/rgbd-scenes-v2/pc/01.ply')

# -----------------------------------------------------------------
# Execution
# -----------------------------------------------------------------

# Matriz de transformação (4x4)
T = [[0.766, -0.643, 0, -0.03], [-0.22, -0.262, -0.94, -0.156], [0.604, 0.72, -0.342, 1.306], [0, 0, 0, 1]]

# Tranformar a pcd 
pcd_downsampled = pcd_downsampled.transform(np.linalg.inv(T))
print(T)

#----------------------
# Visualization 
#----------------------
#criar sistema de coordenadas
frame = o3d.geometry.TriangleMesh().create_coordinate_frame(size=0.5, origin=np.array([0., 0., 0.]))

entities = []
entities.append(frame)
entities.extend([pcd_downsampled])
o3d.visualization.draw_geometries(entities,
                                    zoom=0.3412,
                                    front=view['trajectory'][0]['front'],
                                    lookat=view['trajectory'][0]['lookat'],
                                    up=view['trajectory'][0]['up'])

**Comment by miguelriemoliveira** [comment]
Olá @ritapm18 ,


para começar tentei abrir a nuvem que enviou com o meshlab

![image](https://github.com/miguelriemoliveira/savi_23-24/assets/11350998/2ae5c253-22b7-45a0-97ad-17ce12de931f)


Parece tudo bem.

**Comment by miguelriemoliveira** [comment]
Já carreguei a point cloud com o seu código. De facto não mostra  cores falsas. 

O problema é este

https://github.com/isl-org/Open3D/issues/3100

E a solução é, no cabeçalho do ficheiro, alterar as propriedades 

```
property uchar diffuse_red
property uchar diffuse_green
property uchar diffuse_blue
```
por 

```
property uchar red
property uchar green
property uchar blue
```


difuse_green

Assim já funciona

![image](https://github.com/miguelriemoliveira/savi_23-24/assets/11350998/0631059b-fbb2-4c67-b69e-468f2082960b)

**Comment by miguelriemoliveira** [comment]
Se quiser pode automatizar a substituição dos padrões com o comando sed

https://joshtronic.com/2020/05/09/replacing-multiple-strings-with-sed/

**Comment by ritapm18** [comment]
Muito obrigada professor, já está com as cores corretas :)
