### ISSUE TITLE
Problema a executar código de treino 

### ISSUE THREAD

**Issue by Ze6000** [miguelriemoliveira/savi_23-24#12]
Bom dia professor @miguelriemoliveira, estou de volta do treino e por alguma razão o pc não reconhece a nvidea, o que é estranho mas depois dá erro tambem a usar o pythorch.
O que me aparece no terminal é isto, já instalei e desinstalei o pythorch e tentei ambas as versões disponiveis
![erro](https://github.com/miguelriemoliveira/savi_23-24/assets/88047954/10ba357d-3340-4f9b-9b44-f4ca2d5b38a1)
O que devo fazer agora?

**Comment by miguelriemoliveira** [comment]
Olá @Ze6000 ,

pelo que diz nas mensagens, você não tem a GPU instalada no computador. Talvez a atualização dos drivers ajude.
Outra coisa que pode fazer é correr todo o código no cpu, como mostrei na penultima aula.

**Comment by Ze6000** [comment]
Sim, mas mesmo a usar a cpu não funciona. Eu não terminei o programa, ele é que parou devido áquele erro

**Comment by miguelriemoliveira** [comment]
Suspeito que seja porque está a tentar ativar a gpu algures no seu código. Veja a penultima aula, onde não usei GPU.

Em que linha falha (não envie imagens do terminal, cpoie o texto, é muito máis fácil de ler)?

**Comment by miguelriemoliveira** [comment]
OK, boas notícias.
