### ISSUE TITLE
Dúvidas de interpretação dos objetivos

### ISSUE THREAD

**Issue by mario0vasconcelos** [miguelriemoliveira/savi_23-24#13]
Bom dia professor,

Tenho algumas dúvidas de interpretação relativas a certos objetivos do trabalho e depois a interligação entre estes:

### **Objetivo 1 - Treino de um classificador em deep learning**

- O treino deverá ser feito com as imagens dos objetos isolados, provenientes de "[Cropped RGB and depth images with object segmentation masks](https://rgbd-dataset.cs.washington.edu/dataset/rgbd-dataset)"? Caso **sim**, a validação e o teste também serão com estas imagens? (claro, com a respetiva divisão 80/20% ou 70/2010% como já mencionou noutra issue).

![apple_1_1_1_crop](https://github.com/miguelriemoliveira/savi_23-24/assets/57447959/c45fdad9-f406-4fb2-9bd2-a8f6011fbe55)
 

- O **input** da rede serão imagens como esta? 

![00000-color](https://github.com/miguelriemoliveira/savi_23-24/assets/57447959/5e3a9f80-2267-41ba-8c83-420d6ece5f56)

### **Objetivo 2 - Pre-processamento 3D**

- Tendo a rede treinada e visto que ela irá localizar e classificar objetos na cena, temos de utilizar classificação resultante em combinação com o **labeling** fornecido da núvem de pontos do dataset para obter as propriedades dos objetos? Ou necessitamos de utilizar a localização fornecida pela rede e apartir dai, encontrar as propriedades do objeto pela núvem de pontos (forma dinâmica)?  

- Onde é que a relação IMAGEM RGB -> NUVEM DE PONTOS (ou seja, a POSE) entra para a equação como referido na issue  #11 

> Para isso terão de ter uma imagem e uma nuvem de pontos registadas, quer dizer, em que seja possível ter uma transformação geométrica ou um mapeamento entre elas.  - @miguelriemoliveira 

### **Objetivo 6 - Sistema em tempo real**

- É necessário encontrar as propriedades dos objetos em "tempo real"?

**Comment by miguelriemoliveira** [comment]
Olá @mario0vasconcelos ,

> * O treino deverá ser feito com as imagens dos objetos isolados, provenientes de "[Cropped RGB and depth images with object segmentation masks](https://rgbd-dataset.cs.washington.edu/dataset/rgbd-dataset)"? Caso **sim**, a validação e o teste também serão com estas imagens? (claro, com a respetiva divisão 80/20% ou 70/2010% como já mencionou noutra issue).

Sim, a validação e o teste seriam também com estas imagens. Claro que depois se pretende ver o sistema a funcionar num caso real, e aí também poderá haver uma validação dos resultados (não qualitativa).

> O input da rede serão imagens como esta?

Não. A rede que vos ensinei é apenas um classificador. Quer isto dizer que a rede só consegue fazer a classificação da imagem em caneca, caixa, etc. Se você der uma imagem tão grande quando essa que colocou, com vários objetos na mesa, vai confundir a rede.

As imagens que dá à rede devem ser parecidas com as imagens que usou para treinar, ou seja, imagens só com os objetos e nada mais. Por exemplo a imagem da maçã.

Claro que surge a questão, numa cena com uma imagem com a que você postou, com uma mesa e vários objetos, como é que se arranja uma imagem só com um objeto e nada mais? Para isso pode-se usar a segmentação em 3d e depois tentar encontrar os pixeis na imagem que correspondem apenas ao objeto segmentado.


> Tendo a rede treinada e visto que ela irá localizar e classificar objetos na cena, temos de utilizar classificação resultante em combinação com o labeling fornecido da núvem de pontos do dataset para obter as propriedades dos objetos? Ou necessitamos de utilizar a localização fornecida pela rede e apartir dai, encontrar as propriedades do objeto pela núvem de pontos (forma dinâmica)?

As propriedades dos objetos devem ser calculadas de forma dinâmica. 

> Onde é que a relação IMAGEM RGB -> NUVEM DE PONTOS (ou seja, a POSE) entra para a equação como referido na issue https://github.com/miguelriemoliveira/savi_23-24/issues/11

é aquilo que referi em cima. Depois de ter uma segmentação 3D, é possível perceber quais são na imagem os pixeis que correspondem à nuvem de pontos.

Vou fazer o commit de um código exemplo. Se depois tiver problemas, podemos combinar uma aula extra.


> É necessário encontrar as propriedades dos objetos em "tempo real"?

Sim.

**Comment by miguelriemoliveira** [comment]
Olá @mario0vasconcelos ,

acrescentei aqui 

https://github.com/miguelriemoliveira/savi_23-24/blob/main/Parte12/point_cloud_from_rgbd/main.py

um exemplo de como pode ir de uma imagem rgbd para uma nuvem de pontos e de volta para trás.

**Comment by mario0vasconcelos** [comment]
Ok, creio que está tudo esclarecido.

Obrigado professor @miguelriemoliveira.
