### ISSUE TITLE
Dificuldade na utilização do NiViewer para obter resultados da câmara RGB-D

### ISSUE THREAD

**Issue by Nunoc99** [miguelriemoliveira/savi_23-24#16]
Boa noite professor,

Estou com dificuldades em executar o NiViewer para obter os resultados de profundidade através da câmara, sendo esta uma "Orbbec Astra S". Vi vários vídeos e consultei muitos sites e vi que a maior parte dos utilizadores obtiveram esses resutados através do OpenNi, consegui instalar, no entanto, quando executo para abrir o "NiViewer" diz que não encontra qualquer dispositivo. Vou deixar aqui em baixo um link onde foi debatido este tema e uma das soluções passa por simplesmente alterar um ficheiro ".ini" mas não estou a conseguir alterar devido às permissões, as quais também não consigo alterar. O professor sabe de alguma solução?

A instalação foi feita a partir deste site:
https://structure.io/openni/

O problema foi debatido neste site:
https://github.com/structureio/OpenNI2/issues/88

Também testei esta solução mas não resultou:
https://forums.structure.io/t/no-device-found-openni2-on-ubuntu/8666/2

**Comment by miguelriemoliveira** [comment]
Olá @Nunoc99 ,

o Grupo do Gonçalo Anacleto que apresentou na época normal conseguiu ligar a câmara. Pergunte-lhes como conseguiram.

**Comment by miguelriemoliveira** [comment]
Veja os emails dos colegas na folha com os critérios de avaliação e tente contactá-los.

**Comment by miguelriemoliveira** [comment]
Olá @Nunoc99 ,

pois, não tenho mais ideias. Talvez tentar no computador de um colega do grupo?

Posso também tentar emprestar-lhe uma outra câmara de outra marca, pode ser que ajude.

**Comment by Nunoc99** [comment]
Pode ser que mudando a marca seja possível, só consigo ir à Universidade na sexta, como agilizamos este processo?

**Comment by miguelriemoliveira** [comment]
Olá Nuno,

eu só tenho disponibilidade para a semana ou então podemos combinar por
exemplo no domingo ao fim da tarde / noite.


*  Miguel Riem de Oliveira        Professor Auxiliar         *
email:    ***@***.***    |    ***@***.***
zoom: https://videoconf-colibri.zoom.us/j/7155402102
office: 22.2.18                 |    ext: 23887
Dep. de Engenharia Mecânica, Universidade de Aveiro
*Campus Universitário de Santiago, 3810-193  Portugal*
