### ISSUE TITLE
Imagem dos objetos seguidos

### ISSUE THREAD

**Issue by mario0vasconcelos** [miguelriemoliveira/savi_23-24#17]
Boa noite professor,

Tal como indicado por si na issue #13 , o grupo já conseguiu separar os objetos da nuvem de pontos e na tentativa de obter as imagens dos mesmos, obtivemos o problema existirem multiplos objetos seguidos em algumas cenas, impedindo uma correta classificação da rede.

A seguinte imagem é um dos exempos do problema:
![image](https://github.com/miguelriemoliveira/savi_23-24/assets/57447959/42e4128e-d481-4611-a736-80528aa6b2fc)

Tentamos também obter a imagem diretamente da núvem de pontos mas como é possível verificar, estas não contém detalhe suficiente para serem classificadas.

![image](https://github.com/miguelriemoliveira/savi_23-24/assets/57447959/4963fd81-f2fb-494e-95f9-c4d0f326d469)

Tem alguma recomendação para a resolução do problema?

**Comment by miguelriemoliveira** [comment]
Olá @mario0vasconcelos ,

não percebo muito bem o que quer dizer com 
"problema existirem multiplos objetos seguidos em algumas cenas"

suponho que se refira a oclusões.

A nuvem de pontos é da caneca? Não consigo perceber...
