### ISSUE TITLE
Problemas a guardar o processo no git

### ISSUE THREAD

**Issue by bpeixoto02** [miguelriemoliveira/savi_23-24#2]
Depois de dar commit aparece este erro no push:

![push](https://github.com/miguelriemoliveira/savi_23-24/assets/145439728/16a982fe-6d3c-4a57-a1ba-42075e5443a6)

**Comment by miguelriemoliveira** [comment]
Olá @bpeixoto02 ,

Tem a certeza de que está a colocar a password certa? Tem também um link na mensagem que deve ter instruções.
Recomenda que as leia.

**Comment by bpeixoto02** [comment]
O link diz para informar o sistema do email e usuário mas fica igual.

**Comment by miguelriemoliveira** [comment]
e tem a certeza que a password está certa? Consegue entrar com ela no github?

**Comment by bpeixoto02** [comment]
Sim, o problema não é a password. Se o professor tiver algum horário disponível para reunir presencialmente ou zoom era melhor.

**Comment by miguelriemoliveira** [comment]
Olá @bpeixoto02,

veja isto:

https://dev.to/shafia/support-for-password-authentication-was-removed-please-use-a-personal-access-token-instead-4nbk

**Comment by bpeixoto02** [comment]
Penso que já esteja resolvido.
Obrigado.

**Comment by miguelriemoliveira** [comment]
Olá @bpeixoto02 ,

ok, ainda bem. Duas sugestões:

1. se consegui resolver, digo como fez. Assim ajuda a próxima pessoa que tiver este problema.
2. Quando o assunto está resolvido, feche o issue.

Cumprimentos,
Miguel

**Comment by bpeixoto02** [comment]
Depois de criar o token como mostra o link que o professor enviou colei o token no username pedido quando se faz o push
