### ISSUE TITLE
ex4 - parte 2

### ISSUE THREAD

**Issue by ritapm18** [miguelriemoliveira/savi_23-24#3]
Olá professor,
no ex4 da parte 2 estava a fazer o seguinte:
-> matching template tal como nos exs anteriores
-> converter toda a imagem 'scene' para cinza: scene_grey = cv2.cvtColor(scene, cv2.COLOR_BGR2GRAY)
 e depois queria escolher apenas a zona da imagem em que se encontrou o template e converte-la para cor através de cv2.cvtColor(... cv2.COLOR_GRAY2BGR)
a zona que escolho penso que seja o seguinte: scene_grey[max_loc[0]:max_loc[0]+h, max_loc[1]:max_loc[1]+w]
problema não está a resultar... e diz q o problema é a função cvtColor... mas na outra linha quando converto de bgr para gray funciona

**Comment by miguelriemoliveira** [comment]
Olá @ritapm18 ,

Faça um pequeno exemplo das duas chamadas à função, um que falha e outro que corre bem e coloque aqui o código para eu tentar perceber ...

**Comment by ritapm18** [comment]
import cv2
import numpy

#ler imagem
scene = cv2.imread('/home/rita/Exs_SAVI/parte 2/ex4/scene.jpg') 
#ler template
wally = cv2.imread('/home/rita/Exs_SAVI/parte 2/ex4/wally.png')

#template matching (imagem, template, método)
result = cv2.matchTemplate(scene, wally, cv2.TM_CCOEFF_NORMED)
  
#dá-nos o valor min e máx da matriz 'result' e ainda dá as coordenadas respetivas
_, max_val, _, max_loc = cv2.minMaxLoc(result)

#colocar imagem toda da cena a cinza
scene_grey = cv2.cvtColor(scene, cv2.COLOR_BGR2GRAY)

#mostrar imagens
cv2.imshow('Cena', scene_grey)
cv2.imshow('Template', wally)
cv2.waitKey(0)

quando faço assim funciona

mas se fizer assim:
(...)
#colocar imagem toda da cena a cinza
scene_grey = cv2.cvtColor(scene, cv2.COLOR_BGR2GRAY)

#passar os pixeis em que encontrou o objeto de cinza para cor
h, w, _ = wally.shape
cv2.cvtColor(scene_grey[max_loc[0]:max_loc[0]+h, max_loc[1]:max_loc[1]+w], cv2.COLOR_GRAY2BGR)

#mostrar imagens
cv2.imshow('Cena', scene_grey)
cv2.imshow('Template', wally)
cv2.waitKey(0)

dá me o seguinte erro:
Traceback (most recent call last):
  File "/home/rita/Exs_SAVI/parte 2/ex4/ex4.py", line 20, in <module>
    cv2.cvtColor(scene_grey[max_loc[0]:max_loc[0]+h, max_loc[1]:max_loc[1]+w], cv2.COLOR_GRAY2BGR)
cv2.error: OpenCV(4.6.0) ./modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'

**Comment by miguelriemoliveira** [comment]
Oi @ritapm18 ,

primeiro comentário. Como colocar código nos issues: Copiei o seu código e adaptei. Veja se não fica melhor assim.

```python
import cv25
import numpy

#ler imagem
scene = cv2.imread('/home/rita/Exs_SAVI/parte 2/ex4/scene.jpg')
#ler template
wally = cv2.imread('/home/rita/Exs_SAVI/parte 2/ex4/wally.png')

#template matching (imagem, template, método)
result = cv2.matchTemplate(scene, wally, cv2.TM_CCOEFF_NORMED)

#dá-nos o valor min e máx da matriz 'result' e ainda dá as coordenadas respetivas
_, max_val, _, max_loc = cv2.minMaxLoc(result)

#colocar imagem toda da cena a cinza
scene_grey = cv2.cvtColor(scene, cv2.COLOR_BGR2GRAY)

#mostrar imagens
cv2.imshow('Cena', scene_grey)
cv2.imshow('Template', wally)
cv2.waitKey(0)
```

quando faço assim funciona

mas se fizer assim:
(...)

```python
#colocar imagem toda da cena a cinza
scene_grey = cv2.cvtColor(scene, cv2.COLOR_BGR2GRAY)

#passar os pixeis em que encontrou o objeto de cinza para cor
h, w, _ = wally.shape
cv2.cvtColor(scene_grey[max_loc[0]:max_loc[0]+h, max_loc[1]:max_loc[1]+w], cv2.COLOR_GRAY2BGR)

#mostrar imagens
cv2.imshow('Cena', scene_grey)
cv2.imshow('Template', wally)
cv2.waitKey(0)
```

dá me o seguinte erro:

```terminal
Traceback (most recent call last):
File "/home/rita/Exs_SAVI/parte 2/ex4/ex4.py", line 20, in
cv2.cvtColor(scene_grey[max_loc[0]:max_loc[0]+h, max_loc[1]:max_loc[1]+w], cv2.COLOR_GRAY2BGR)
cv2.error: OpenCV(4.6.0) ./modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'
```

Isto ajuda muito quem a está a ajudar a perceber o problema.

**Comment by miguelriemoliveira** [comment]
Quanto ao erro, parece que é a src da função cvtcolor que está vazia ...

Pode tentar isto:

```python
img_tmp = scene_grey[max_loc[0]:max_loc[0]+h, max_loc[1]:max_loc[1]+w]
cv2.imshow('img_tmp', img_tmp)
cv2.waitKey(0)
```

Para validar a parte da extração de parte da scene_grey ...
