### ISSUE TITLE
Diferença entre matrizes

### ISSUE THREAD

**Issue by brunofavs** [miguelriemoliveira/savi_23-24#4]
Olá

Estou com uma dúvida algo abstrata : 

Quando uso este código para calcular diferença entre 2 ROI's:

`difference_roi = cv2.absdiff(image_roi,previous_image_roi)`

Funciona bem e mostra a diferença como eu esperava : 
![image](https://github.com/miguelriemoliveira/savi_23-24/assets/31831043/84b81153-19ea-49c3-8d30-7c8cb2b9e138)

Mas se usar esta linha que me parece igual, de acordo com a wiki do openCV ["Calculates the per-element absolute difference between two arrays or between an array and a scalar." ](https://shimat.github.io/opencvsharp_docs/html/6c7cefd1-59bc-a595-fe2a-0c8a709f8d16.htm) :
`difference_roi = np.abs(image_roi - previous_image_roi)`

O código não dá erro mas aparece esta salganhada :

![image](https://github.com/miguelriemoliveira/savi_23-24/assets/31831043/85cbbba5-ea07-45a5-bc48-32ae50d2820a)

 A que se deve este comportamento e qual é a diferença entre as duas linhas de código?

Obrigado a quem gastar tempo a ajudar :) 

Edit : Eu entretanto reparei que estava a calcular os ROI's com as imagens RGB por engano, o que já mudei mas o problema mantém-se.

**Comment by miguelriemoliveira** [comment]
Olá @brunofavs ,

o que provavelmente está a acontecer são [underflows e overflows](https://www.educative.io/answers/what-are-overflow-and-underflow), como expliquei na aula 2.

Julgo que a função cv2.absdiff(image_roi,previous_image_roi) deve ter uma proteção contra underflows e overflows, que a subtração em numpy não terá.

Para confirmar pode fazer a conversão para float para evitar overflows, depois saturar, e finalmente converter para uint8 outra vez.

```python

difference_roi_float = image_roi.astype(float) - previous_image_roi.astype(float)

# Avoid underflows
mask_underflows = difference_roi_float < 0
difference_roi_float[mask_underflows] = 0

# Avoid overflows
mask_overflows = difference_roi_float > 255
difference_roi_float[mask_overflows] = 255

# Convert back to uint8
difference_roi = different_roi_float.astype(uint8)
```

Funciona?

**Comment by brunofavs** [comment]
Olá @miguelriemoliveira !

AAAH já entendi !
Eu pensava que o `cv2.abs()` estava a proteger conta os underflows/overflows mas o facto é que já estou a dar input a essa função um valor "estragado", ou seja que já pode ter sofrido underflows/overflows.

E experimentei a sua solução e de facto resolve, dando o mesmo resultado que a `cv2.absdiff()`

Obrigado!
