### ISSUE TITLE
Aula de compensação

### ISSUE THREAD

**Issue by JoseSilva23** [miguelriemoliveira/savi_23-24#5]
Bom dia,
o professor marcou a aula de compensação para sexta-feira das 9h -12h que é quando eu e mais um colega temos aula (das 9h-11h e das 11h-13h). Se formos os únicos com sobreposição vêmos a gravação da aula.
José Silva

**Comment by miguelriemoliveira** [comment]
Olá José,

pois, imagino que para outros colegas também haja sobreposição, mas podem depois ver o vídeo e se for preciso marcar comigo depois para tirar dúvidas.

Obrigado,
Miguel
