### ISSUE TITLE
Dúvida acerca dos Datasets

### ISSUE THREAD

**Issue by RBastos36** [miguelriemoliveira/savi_23-24#9]
Boa tarde professor @miguelriemoliveira, 

Ao explorar o site dos _Datasets_ que o professor indicou, deparámo-nos com uma dúvida. Nas _scenes_ presentes em _RGB-D Scenes Dataset v.2_, é dito que apenas contem alguns dos objetos dos _Datasets Objetcs_ (_bowls, caps, cereal boxes, coffee mugs, and soda cans_).

Mas, ao explorar a secção _RGB-D Object Dataset_, é possível verificar que, apesar de existirem vários objetos na secção _[Cropped RGB and depth images with object segmentation masks](https://rgbd-dataset.cs.washington.edu/dataset/rgbd-dataset)_, na secção [Evaluation Set (Subsampled turntable frames as used in our RGB-D object recognition experiments)](https://rgbd-dataset.cs.washington.edu/dataset/rgbd-dataset_eval) apenas se encontra um dos objetos referidos para teste (_coffee mug_).

Como devemos proceder para testar o nosso modelo de treino? Como primeira solução treinámos o nosso modelo utilizando apenas os tipos de objetos referidos nas cenas com uma divisão de 80/20 para treino/teste. Aqui surgiu o problema de, como as imagens de cada pasta são o mesmo objeto em várias posições, com algum treino, o modelo passava no teste com scores perfeitos ou quase perfeitos, visto que no teste, os objetos seriam iguais, mas com orientações diferentes. Caso contrário, se o treino for muito reduzido (5 ou 6 épocas), os resultados já mostram uma precisão mais reduzida.

**Comment by miguelriemoliveira** [comment]
Olá @RBastos36 ,

o que sugiro é que, tal como aconteceu no dataset de cats and dogs no exemplo que dei na aula, façam vocês mesmos a divisão do train dataset original em train, validation e test datasets. 

Assim já consegue ter vários objetos, certo?

**Comment by RBastos36** [comment]
Obrigado pelo esclarecimento.

Só um aparte, assim não poderemos garantir os 80/20 por cento para o treino/teste, visto que necessitaríamos de dividir por objetos dentro da mesma classe (ex: [bowl_1.tar](https://rgbd-dataset.cs.washington.edu/dataset/rgbd-dataset/bowl_1.tar); [bowl_2.tar](https://rgbd-dataset.cs.washington.edu/dataset/rgbd-dataset/bowl_2.tar); [bowl_3.tar](https://rgbd-dataset.cs.washington.edu/dataset/rgbd-dataset/bowl_3.tar); [bowl_4.tar](https://rgbd-dataset.cs.washington.edu/dataset/rgbd-dataset/bowl_4.tar) e [bowl_5.tar](https://rgbd-dataset.cs.washington.edu/dataset/rgbd-dataset/bowl_5.tar) para treino, e para teste apenas [bowl_6.tar](https://rgbd-dataset.cs.washington.edu/dataset/rgbd-dataset/bowl_6.tar), visto que cada uma das pastas é apenas um objeto com várias orientações).

**Comment by miguelriemoliveira** [comment]
Olá @RBastos36 ,

Talvez eu não esteja a perceber bem o problema. Não têm mais do que um objeto? O que sugiro é que juntem todos os objetos labeled que têm numa pasta só, vamos chamar a pasta **raw**. Vai ter por exemplo

bowl_1
bowl_2
bowl_3
mug_1
mug_2
mug_3
bottle_1
bootle_2
bootle_3
bootle_4

Depois criam 3 datasets, treino, validação e teste, randomizando 70,20 e 10% destes ficheiros.
Ficaria por exemplo:

**Treino**

bowl_2
bowl_3
mug_1
mug_3
bootle_1
bootle_2
bootle_3

**Validação**

bowl_1
mug_2

**Teste**

bootle_4

Claro que este exemplo só faria sentido com no mínimo centenas de objetos.

**Comment by RBastos36** [comment]
Exato, foi essa a proposta que eu disse na resposta anterior. Mas pelo que consegui verificar, cada uma dessas pastas apenas contém um objeto, mas com várias fotos em várias orientações.

Uma dúvida adicional, não existe problema em criar um dataset de teste ou validação que não possua todos os objetos de treino? Porque depois irá dar problemas para as métricas no teste devido à falta de teste de determinados objetos.

**Comment by miguelriemoliveira** [comment]
Olá @RBastos36 ,

> Exato, foi essa a proposta que eu disse na resposta anterior. Mas pelo que consegui verificar, cada uma dessas pastas apenas contém um objeto, mas com várias fotos em várias orientações.

Mas se juntar o conteúdo das várias pastas, não fica com vários objetos? O que chamos de pasta **raw** acima?

> Uma dúvida adicional, não existe problema em criar um dataset de teste ou validação que não possua todos os objetos de treino? Porque depois irá dar problemas para as métricas no teste devido à falta de teste de determinados objetos.

Sim. Isso chama-se "class inbalance". Sugiro que tenha o cuidado de ter uma divisão mais ou menos consistente entre as classes de objetos. Pode por exemplo aplicar o algoritmo que dei acima para uma pasta raw de cada classe, separar em treino, validação e teste separadamente para cada classe, o apenas no final juntar todos os treinos, validações e testes.

**Comment by RBastos36** [comment]
> Mas se juntar o conteúdo das várias pastas, não fica com vários objetos? O que chamos de pasta raw acima?

Pasta raw seria a pasta com os vários objetos. Mas, por exemplo, no caso das bowls, teria apenas 5 bowls diferentes, mas centenas de fotos para cada uma, sendo estas fotos em várias posições.

> Sim. Isso chama-se "class inbalance". Sugiro que tenha o cuidado de ter uma divisão mais ou menos consistente entre as classes de objetos. Pode por exemplo aplicar o algoritmo que dei acima para uma pasta raw de cada classe, separar em treino, validação e teste separadamente para cada classe, o apenas no final juntar todos os treinos, validações e testes.

Ok professor, vamos tentar implementar isso de forma a não criar esses desequilíbrios de classes.

**Comment by RBastos36** [comment]
Bom dia professor. Penso que já conseguimos fazer com que os desequilíbrios do modelo desaparecessem, pelo menos maioritariamente.

Obrigado pela ajuda e disponibilidade.
